apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: default
data:
  elasticsearch.yml: |
    cluster.name: "hellogithubactions-cluster"
    node.name: "hellogithubactions-es-node"
    
    # Network settings
    network.host: 0.0.0.0
    http.port: 9200
    transport.port: 9300
    
    # Discovery settings for single node
    discovery.type: single-node
    
    # Performance optimizations
    # Memory settings
    bootstrap.memory_lock: true
    
    # Index settings for performance
    indices.memory.index_buffer_size: 20%
    indices.memory.min_index_buffer_size: 96mb
    indices.fielddata.cache.size: 20%
    indices.queries.cache.size: 10%
    indices.requests.cache.size: 2%
    
    # Thread pool settings for indexing performance
    thread_pool.write.size: 2
    thread_pool.write.queue_size: 1000
    thread_pool.search.size: 3
    thread_pool.search.queue_size: 1000
    
    # Bulk settings for high throughput
    action.auto_create_index: true
    
    # Circuit breaker settings
    indices.breaker.total.limit: 70%
    indices.breaker.fielddata.limit: 40%
    indices.breaker.request.limit: 40%
    
    # Logging level
    logger.level: INFO
    
    # Disable X-Pack security for development
    xpack.security.enabled: false
    xpack.security.enrollment.enabled: false
    xpack.ml.enabled: false
    xpack.graph.enabled: false
    xpack.watcher.enabled: false
    
    # Performance monitoring
    xpack.monitoring.collection.enabled: true
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-optimized
  namespace: default
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      initContainers:
      - name: configure-sysctl
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
        command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
        ports:
        - containerPort: 9200
        - containerPort: 9300
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 1000m
            memory: 4Gi
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms2g -Xmx2g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+DisableExplicitGC"
        - name: discovery.type
          value: single-node
        - name: xpack.security.enabled
          value: "false"
        - name: xpack.security.enrollment.enabled
          value: "false"
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        - name: config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
          readOnly: true
        readinessProbe:
          httpGet:
            path: /_cluster/health?wait_for_status=yellow&timeout=5s
            port: 9200
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
      volumes:
      - name: config
        configMap:
          name: elasticsearch-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ""
      resources:
        requests:
          storage: 20Gi